content:
  application/json:
    schema:
      type: object
      properties:
        projectNo:
          type: integer
        projectName:
          type: string
        createDate:
          type: string